import boto3

name: cicd automation

on:
  push:
    branches: [master]
  pull-request:
    branches: [master]

jobs:
  build:

    runs-on: ${{matrix.os}} 
    stategy:
      matrix: [ubuntu-latest, windows-latest, macOS-latest ]
        os:
    steps:
    -uses: actions/checkout@v2
    -name: set up jdk 1.8
     uses: actions/setup-java@1.8
      with: 
        java-version: 1.8
    -name: grant execute permission for gradlew
     run: chmod +x gradlew

    -name: build with gradlew
     run: ./gradlew build
publish:

    needs: build